cc_library(
    name = "ellipsis",
    hdrs = [
        "ellipsis.hpp",
    ],
    deps = [
        "//bark/commons:commons",
        "@com_github_eigen_eigen//:eigen",
    ],
    visibility = ["//visibility:public"],
)